version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: cinema-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis-server

